/**
 * Catering SQL - Output adapter untuk format SQL dump
 */

import { writeFileSync, existsSync } from "node:fs";
import { PESAN, format } from "../pesan.js";

/**
 * Class CateringSQL
 */
export class CateringSQL {
    constructor(options = {}) {
        this.options = {
            dialect: "postgres", // postgres, mysql
            batchSize: 100,
            timpa: false,
            ...options,
        };
    }

    /**
     * Escape nilai untuk SQL
     * @param {*} value
     * @returns {string}
     */
    _escape(value) {
        if (value === null || value === undefined) {
            return "NULL";
        }

        if (typeof value === "boolean") {
            return value ? "TRUE" : "FALSE";
        }

        if (typeof value === "number") {
            return String(value);
        }

        // String - escape single quotes
        const str = String(value).replace(/'/g, "''");
        return `'${str}'`;
    }

    /**
     * Generate SQL INSERT statements
     * @param {object[]} data
     * @param {string} tableName
     * @returns {string}
     */
    toString(data, tableName = "data") {
        if (!data || data.length === 0) {
            return "-- No data to insert\n";
        }

        const lines = [];
        const columns = Object.keys(data[0]);
        const columnList = columns.join(", ");

        lines.push(`-- Generated by MBG Database Seeder`);
        lines.push(`-- Table: ${tableName}`);
        lines.push(`-- Records: ${data.length}`);
        lines.push("");

        // Batch inserts
        const batchSize = this.options.batchSize;
        for (let i = 0; i < data.length; i += batchSize) {
            const batch = data.slice(i, i + batchSize);

            lines.push(`INSERT INTO ${tableName} (${columnList}) VALUES`);

            const valueLines = batch.map((row, idx) => {
                const values = columns.map((col) => this._escape(row[col]));
                const suffix = idx === batch.length - 1 ? ";" : ",";
                return `  (${values.join(", ")})${suffix}`;
            });

            lines.push(...valueLines);
            lines.push("");
        }

        return lines.join("\n");
    }

    /**
     * Tulis data ke file SQL
     * @param {object[]} data
     * @param {string} filePath
     * @param {string} tableName
     * @returns {{success: boolean, path: string, size: number}}
     */
    tulis(data, filePath, tableName = "data") {
        // Cek file exists
        if (!this.options.timpa && existsSync(filePath)) {
            throw new Error(format(PESAN.OUTPUT_EXISTS, { file: filePath }));
        }

        const content = this.toString(data, tableName);
        writeFileSync(filePath, content, "utf-8");

        return {
            success: true,
            path: filePath,
            size: Buffer.byteLength(content, "utf-8"),
        };
    }
}

export default CateringSQL;
